/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ThoughtsIndexImport } from './routes/thoughts.index'
import { Route as ThoughtsSlugImport } from './routes/thoughts.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThoughtsIndexRoute = ThoughtsIndexImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => rootRoute,
} as any)

const ThoughtsSlugRoute = ThoughtsSlugImport.update({
  id: '/thoughts/$slug',
  path: '/thoughts/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/thoughts/$slug': {
      id: '/thoughts/$slug'
      path: '/thoughts/$slug'
      fullPath: '/thoughts/$slug'
      preLoaderRoute: typeof ThoughtsSlugImport
      parentRoute: typeof rootRoute
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/thoughts': typeof ThoughtsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/thoughts': typeof ThoughtsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thoughts/$slug' | '/thoughts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thoughts/$slug' | '/thoughts'
  id: '__root__' | '/' | '/thoughts/$slug' | '/thoughts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThoughtsSlugRoute: typeof ThoughtsSlugRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThoughtsSlugRoute: ThoughtsSlugRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/thoughts/$slug",
        "/thoughts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/thoughts/$slug": {
      "filePath": "thoughts.$slug.tsx"
    },
    "/thoughts/": {
      "filePath": "thoughts.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
